export interface FaqItem {
  id: string;
  category: string;
  question: string;
  answer: string;
}

export const ALL_FAQS: FaqItem[] = [
  // Devices
  { id: "f1",  category: "Devices",  question: "What devices work with an IPTV UK subscription?", answer: "Our IPTV UK subscription works on virtually every modern device — Amazon Fire Stick, Android TV boxes, Smart TVs (Samsung, LG, Sony), iOS and Android phones and tablets, Windows and Mac computers, MAG boxes, and Kodi. If it runs a player app like TiviMate, IPTV Smarters, or Perfect Player, it works. No specialist hardware is required — if you already stream Netflix, you're already set up." },
  { id: "f2",  category: "Devices",  question: "What IPTV player app do you recommend?", answer: "For Amazon Fire Stick and Android TV, TiviMate is our top recommendation — it has the best EPG experience, multi-screen view, and catch-up TV support. For iOS, GSE Smart IPTV is excellent. IPTV Smarters Pro works across all platforms and is a great all-rounder. All recommended apps are free or low-cost, and our setup guides walk you through configuring each one step by step." },
  // Getting started
  { id: "f3",  category: "Getting Started", question: "How quickly can I start watching after subscribing?", answer: "Instantly. Once payment is confirmed, your M3U playlist URL and account credentials are delivered by email within minutes. Load them into your preferred IPTV player app and you're streaming. Most customers are watching their first channel within 5 minutes. Step-by-step setup guides cover every device. If you run into anything, our 24/7 support team typically responds within the hour." },
  { id: "f4",  category: "Getting Started", question: "How do I access my credentials after purchase?", answer: "Your M3U URL, username, and password are delivered to your registered email address within minutes of payment confirmation. Check your spam folder if you don't see it within 15 minutes. You can also retrieve your credentials at any time by contacting our support team with your registered email address. We do not store plaintext passwords — credentials are generated at the time of subscription." },
  // Trial & Billing
  { id: "f5",  category: "Trial & Billing", question: "Do you offer a free trial?", answer: "Yes — we offer a 24-hour free trial so you can test our IPTV UK subscription before committing. Contact our support team via live chat or email to request your trial. No credit card required. This lets you verify stream quality, channel availability, and device compatibility. If you're satisfied — and the vast majority of trial users subscribe — you can upgrade directly from the trial account." },
  { id: "f6",  category: "Trial & Billing", question: "What's your refund policy?", answer: "We offer a 7-day money-back guarantee on all plans. If you're not satisfied with our IPTV UK subscription for any reason within 7 days of purchase, contact our support team for a full refund — no questions asked. Refunds are processed within 3–5 business days. Beyond 7 days, refunds are assessed individually. Full terms are on our Refund Policy page." },
  { id: "f7",  category: "Trial & Billing", question: "What payment methods do you accept?", answer: "We accept all major credit and debit cards (Visa, Mastercard, Amex), PayPal, and cryptocurrency. All payments are processed through encrypted, PCI-compliant gateways. We never store card details on our servers. All prices are inclusive of UK VAT — the price shown is the final amount you pay at checkout, with no hidden charges added." },
  { id: "f8",  category: "Trial & Billing", question: "Can I upgrade or downgrade my plan?", answer: "Yes, you can change your plan at any point. To upgrade, purchase the new plan and contact support — remaining value from your current plan is credited pro-rata. To downgrade, let your current subscription run its course and renew at the lower tier. Many customers start on Starter to test the service, then upgrade to Silver or Golden when they're ready to commit longer-term." },
  // Channels
  { id: "f9",  category: "Channels", question: "How many channels are included in an IPTV UK subscription?", answer: "Every IPTV UK subscription plan includes 35,000+ live channels. This covers all UK terrestrials (BBC, ITV, Channel 4, Channel 5), full Sky Sports and TNT Sports packages, Sky Cinema, discovery+, and international channels from 150+ countries. Sports channels include dedicated Premier League, Champions League, F1, boxing, and UFC feeds. You also get 100,000+ on-demand movies and TV shows — all included in your single subscription." },
  { id: "f10", category: "Channels", question: "Are Sky Sports channels included?", answer: "Yes — all Sky Sports channels are included in every plan. This covers Sky Sports Premier League, Sky Sports Football, Sky Sports Cricket, Sky Sports Golf, Sky Sports F1 (in 4K on Silver/Golden), Sky Sports Arena, Sky Sports Main Event, and Sky Sports Racing. TNT Sports 1–4 and Eurosport 1 & 2 are also included. There are no sports add-ons or PPV upgrade fees — it's all in the base subscription." },
  { id: "f11", category: "Channels", question: "Can I get channels from my home country?", answer: "Our IPTV UK subscription includes channels from 150+ countries. Whether you're looking for Arabic news (MBC1, Al Arabiya), Indian entertainment (Zee TV, Star Plus, Colors), French television (TF1, M6), German channels (ARD, ZDF, RTL), Italian (Rai Uno), Spanish (Antena 3, TVE), or dozens of other regional packages, they're all included. Check our full channel list to confirm your preferred country is covered." },
  // Streaming Quality
  { id: "f12", category: "Streaming Quality", question: "Will channels buffer during live sport?", answer: "Our infrastructure is built for peak-demand events — Premier League kick-offs, Champions League finals, and major boxing nights. Our anti-freeze buffer technology pre-loads stream frames in real time to prevent interruptions. On a stable 20 Mbps+ connection, buffering is essentially eliminated. Thousands of UK subscribers watch live football every weekend without a single dropout. If issues occur, support resolves them immediately." },
  { id: "f13", category: "Streaming Quality", question: "Can I stream in 4K Ultra HD?", answer: "Yes, 4K Ultra HD streams are available on Silver and Golden plans. You'll need a 4K-compatible device (4K Fire Stick, Android TV box, or 4K Smart TV), a compatible IPTV player app, and a broadband connection of 50 Mbps or above. Our 4K channels include select Premier League matches, Sky Cinema Premiere content, Sky Sports F1, and major sporting events. HD streams are available on all plans including Starter." },
  { id: "f14", category: "Streaming Quality", question: "What internet speed do I need?", answer: "For standard HD channels, a stable 10 Mbps connection is sufficient. For Full HD (1080p), 20 Mbps is recommended. For 4K Ultra HD streams, you'll want at least 50 Mbps for a buffer-free experience. Most UK broadband packages — including standard BT, Virgin, Sky, and TalkTalk connections — comfortably exceed these requirements. A wired ethernet connection is always preferable to Wi-Fi for live sport." },
  { id: "f15", category: "Streaming Quality", question: "Does the service include an Electronic Programme Guide?", answer: "Yes, all plans include a full 7-day EPG. The Electronic Programme Guide shows current and upcoming programmes for every channel, similar to the TV Guide function on traditional platforms. To access EPG, use a compatible player app — TiviMate or IPTV Smarters both support automatic EPG refresh. If your EPG isn't loading, our support team can help configure your EPG URL correctly within minutes." },
  // Features
  { id: "f16", category: "Features", question: "What is catch-up TV and which plans include it?", answer: "Catch-up TV lets you watch programmes that already aired — typically up to 7 days in the past. On Silver and Golden plans, catch-up is available for participating channels, letting you rewatch Premier League matches, episodes you missed, and live events. To access catch-up, use TiviMate or IPTV Smarters and look for the backward-facing arrow icon on supported channels. The Starter plan does not include catch-up." },
  { id: "f17", category: "Features", question: "Can I use a VPN with your service?", answer: "Yes, our IPTV UK subscription is fully compatible with VPNs. A VPN can enhance privacy and reduce ISP throttling that sometimes affects stream quality. For best results, connect to a UK-based VPN server — this ensures the lowest latency and full access to region-specific channels. NordVPN, ExpressVPN, and Surfshark all work reliably with our service. If you notice buffering on VPN, switching to a closer UK server usually resolves it." },
  { id: "f18", category: "Features", question: "Will my subscription work when I travel abroad?", answer: "Yes, your IPTV UK subscription works in most countries worldwide as long as you have a stable internet connection. Some countries restrict certain streaming content, and local ISPs may throttle IPTV traffic — a VPN connected to a UK server resolves both issues. Set up your service at home before travelling and test it fully. Contact support if you experience geo-blocking issues in a specific destination country." },
  // Legal & Support
  { id: "f19", category: "Legal & Support", question: "Is IPTV legal in the UK?", answer: "IPTV technology is entirely legal — it's the same delivery method used by Netflix, BBC iPlayer, and Sky Go. What matters legally is the content being accessed. We provide a technical streaming service; subscribers are responsible for ensuring their usage complies with applicable UK broadcasting regulations. If you have specific concerns about content licensing in your region, we recommend seeking independent legal advice." },
  { id: "f20", category: "Legal & Support", question: "How do I contact customer support?", answer: "Our support team is available 24/7 via live chat on our website and by email at support@iptvuksubscription.uk. The average response time is under one hour. For urgent issues during live sport, use live chat for the fastest response. We also maintain a comprehensive setup guide and FAQ to help you resolve common issues independently. A human responds to every support ticket — we don't use bot-only support." },
];
